### ISSUE TITLE
ncdev tool not (yet?) on pip?

### ISSUE THREAD

**Issue by ccoenen** [nextcloud/ncdev#10]
I am trying to get ncdev to run with the instructions from the README.

```
# pip3 install ncdev
Collecting ncdev
  Could not find a version that satisfies the requirement ncdev (from versions: )
No matching distribution found for ncdev
```

Python is not exactly my strongest language, so I may very well be wrong. If there's something I'm overlooking, please let me know!

```
# pip3 search ncdev
# pip3 search ocdev
ocdev (0.2.2)    - ownCloud development tool
pyprocdev (0.2)  - Python interface to /proc/devices
```

**Comment by chrsch** [comment]
I just wondered the same. On Windows this time. ocdev is through pip.

**Comment by BernhardPosselt** [comment]
dup of #9

**Comment by ccoenen** [comment]
Sorry, as a newbie to python, it was not obvious to me that PyPi === pip.
