### ISSUE TITLE
"ncdev setup base" does not work

### ISSUE THREAD

**Issue by janibonnevier** [nextcloud/ncdev#6]
The command `ncdev setup base` does not seem to work like described in the README. Whether it's the README or the program that is wrong, I don't know.

```
$ ncdev setup base

Selected setup type is not server. Trying to clone repository named base

Cloning into 'base'...
[ github login ]
remote: Repository not found.
fatal: repository 'https://github.com/server/base.git/' not found
Cloning into 'base'...
```

**Comment by janibonnevier** [comment]
The problem might be at `plugins/setup/setup.py` line 80:
`'repo': 'https://github.com/server/%s.git' % level,`

But where is the "base" repo?

**Comment by BernhardPosselt** [comment]
should be 

    ncdev setup server

now :)

We've reordered some things
